### ISSUE TITLE
Clipped Phylum UI URL

### ISSUE THREAD

**Issue by furi0us333** [phylum-dev/phylum-ci#140]
## Describe the bug

When using GitLab branch pipelines, the output in the logs clips the Phylum UI URL causing it to not work properly. This seems to be a formatting oddity, the intended URL looks correct.

## To Reproduce

1. Go to the output of a GitLab branch pipeline job with Phylum issue
2. See the URL clipping at the bottom of the phylum summary

## Expected behavior

If provided as a clickable URL, the URL leads to the proper location.

## Screenshots

![image](https://user-images.githubusercontent.com/34108612/195118583-55870f33-760d-4117-93f1-6a2b2141e7ef.png)

**Comment by maxrake** [comment]
Ah...yes, that is due to the way the `connect-markdown-renderer` and `rich` libraries render the markdown in a terminal. I believe the width is automatically determined (maybe via environment variable) and for this CI environment, the width is smaller than the link, causing it to get clipped.

The library method in use now does not allow for specifying different behavior. Instead, it might be possible to simply move that link output to be outside of the markdown results output. That can happen universally or by determining when the operating environment is a console instead of a UI (e.g., comment on a PR).
