### ISSUE TITLE
`Issue Summary` data missing for vulnerability domain

### ISSUE THREAD

**Issue by furi0us333** [phylum-dev/phylum-ci#98]
## Describe the bug

`Issue Summary` data seems to be missing for vulnerabilities.

## To Reproduce

1. Submit failing analysis that contains a vuln
2. Observe the MR/PR comment with missing `Issue Summary` data

## Expected behavior

`Issue Summary` data is populated for all issues.

## Screenshots
![image](https://user-images.githubusercontent.com/34108612/184266168-14d69509-7257-4ad7-a75a-1120770dd750.png)

## Additional context

I check a license issue and the summary data was present, but I did not check other risk domains. There is a chance this is only impact vulnerability issues.

**Comment by maxrake** [comment]
@furi0us333, found the issue...fix coming today. It has likely been a problem since #94 was completed a bit over a week ago. The fix this time will attempt to straddle the different naming differences in a way that _should not_ bite us again when the API makes the change back to using `vulnerability` instead of `vulnerabilities` 🤞
